// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial1;

namespace Parcial1.Migrations
{
    [DbContext(typeof(Tareasdbcontext))]
    [Migration("20201010145947_iniciall")]
    partial class iniciall
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Parcial1.Detalles", b =>
                {
                    b.Property<string>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recurso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tiempo")
                        .HasColumnType("TEXT");

                    b.HasKey("Fecha");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("Parcial1.Recursos", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioPK")
                        .HasColumnType("INTEGER");

                    b.HasKey("Nombre");

                    b.HasIndex("UsuarioPK");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("Parcial1.Tareas", b =>
                {
                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(50);

                    b.Property<int>("Estimacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsable")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vencimiento")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Titulo");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("Parcial1.Usuarios", b =>
                {
                    b.Property<int>("UsuarioPK")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnName("Password")
                        .HasColumnType("char(20)");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("UsuarioPK");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Parcial1.Recursos", b =>
                {
                    b.HasOne("Parcial1.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioPK");
                });
#pragma warning restore 612, 618
        }
    }
}
